/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_apon_opuscodec_OpusDecoder */

#ifndef _Included_me_apon_opuscodec_OpusDecoder
#define _Included_me_apon_opuscodec_OpusDecoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     me_apon_opuscodec_OpusDecoder
 * Method:    init
 * Signature: (III)Z
 */
JNIEXPORT jboolean JNICALL Java_me_apon_opuscodec_OpusDecoder_init
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     me_apon_opuscodec_OpusDecoder
 * Method:    decode
 * Signature: ([B[S)I
 */
JNIEXPORT jint JNICALL Java_me_apon_opuscodec_OpusDecoder_decode
  (JNIEnv *, jclass, jbyteArray, jshortArray);

/*
 * Class:     me_apon_opuscodec_OpusDecoder
 * Method:    close
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_me_apon_opuscodec_OpusDecoder_close
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
